# Android builds the same game libraries; only entry, device I/O and the window backend differ.
find_package(OpenXR REQUIRED CONFIG)
find_library(GT2_VULKAN vulkan REQUIRED)
find_program(GT2_GLSLC glslc HINTS "$ENV{VULKAN_SDK}/Bin" REQUIRED NO_CMAKE_FIND_ROOT_PATH)
set(GT2VK_SHADER_DIR "${CMAKE_CURRENT_BINARY_DIR}/shaders")
file(MAKE_DIRECTORY "${GT2VK_SHADER_DIR}")
set(GT2VK_SHADER_OUTPUTS)
foreach(shader scene.vert scene.frag scene_cached.frag)
  set(out "${GT2VK_SHADER_DIR}/${shader}.inc")
  add_custom_command(OUTPUT "${out}" COMMAND "${GT2_GLSLC}" -O -mfmt=c -o "${out}" "${CMAKE_CURRENT_SOURCE_DIR}/src/gt2view/shaders/${shader}"
    DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/gt2view/shaders/${shader}" VERBATIM)
  list(APPEND GT2VK_SHADER_OUTPUTS "${out}")
endforeach()
include(cmake/stereo-shaders.cmake)
add_library(gt2vk STATIC src/gt2view/vk_context_android.cpp src/gt2view/vk_scene_renderer.cpp src/gt2view/render_capture.cpp src/gt2view/decoded_textures.cpp src/gt2view/stereo_foveation.cpp src/gt2view/hud.cpp
  src/gt2view/particles.cpp src/gt2view/glow.cpp src/gt2view/menu_view.cpp src/gt2view/title_view.cpp
  src/gt2view/panel_view.cpp src/gt2view/race_overlay_screens.cpp src/gt2view/movie_view.cpp ${GT2VK_SHADER_OUTPUTS})
include(cmake/vr-hand-assets.cmake)
target_include_directories(gt2vk PRIVATE "${GT2VK_SHADER_DIR}")
target_link_libraries(gt2vk PUBLIC gt2export ${GT2_VULKAN})
add_library(gt2os STATIC src/platform/os/paths_android.cpp)
target_include_directories(gt2os PUBLIC src)
add_library(gt2xr STATIC src/platform/xr/xr_session.cpp src/platform/xr/vr_rig.cpp src/platform/xr/vr_driving.cpp src/platform/xr/xr_actions.cpp)
target_include_directories(gt2xr PUBLIC src PRIVATE third_party/openxr/include)
target_link_libraries(gt2xr PUBLIC ${GT2_VULKAN} OpenXR::openxr_loader)
add_library(gt2inputdev STATIC src/platform/input/input_system_android.cpp)
target_link_libraries(gt2inputdev PUBLIC gt2input log)
add_library(gt2_native_glue STATIC "${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c")
target_compile_options(gt2_native_glue PRIVATE -Wno-unused-parameter)
target_include_directories(gt2_native_glue PUBLIC "${ANDROID_NDK}/sources/android/native_app_glue")
file(GLOB GT2GAME_CPP CONFIGURE_DEPENDS tools/gt2game/*.cpp)
list(FILTER GT2GAME_CPP EXCLUDE REGEX "/(main|game_window_win32|game_window_xr)\\.cpp$")
add_library(gt2game SHARED ${GT2GAME_CPP} ${GT2_DEV_DUMP_SOURCES} android/app/src/main/cpp/android_main.cpp)
target_include_directories(gt2game PRIVATE tools/gt2game)
target_link_libraries(gt2game PRIVATE gt2vfs gt2formats gt2export gt2gamelib gt2audio gt2career gt2menu gt2shell
  gt2screens gt2camera gt2arcade gt2vk gt2xr gt2inputdev gt2os gt2_native_glue android log)
target_link_options(gt2game PRIVATE "-Wl,-u,ANativeActivity_onCreate")

add_executable(gt2renderbench tools/gt2renderbench/main.cpp)
target_link_libraries(gt2renderbench PRIVATE gt2vk gt2xr)
