enable_language(OBJCXX)
add_executable(gt2maclauncher tools/gt2mac/launcher.mm)
set_target_properties(gt2maclauncher PROPERTIES OBJCXX_STANDARD 20 OBJCXX_STANDARD_REQUIRED ON)
target_compile_options(gt2maclauncher PRIVATE -fobjc-arc)
target_link_libraries(gt2maclauncher PRIVATE "-framework Cocoa")
include(cmake/sdl-client.cmake)
foreach(target gt2game gt2install gt2media gt2maclauncher)
  target_link_options(${target} PRIVATE -Wl,-headerpad_max_install_names)
endforeach()
if(BUILD_TESTING)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  add_test(NAME macos_hd_preparation_checks
    COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/macos_hd_checks.py")
  add_test(NAME macos_package_checks
    COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_CURRENT_SOURCE_DIR}/tests/macos_package_checks.py")
endif()
