#pragma once
// The GTE operations the native re-implementations of the original's drawers need, bit-exact to the PS1 (FLAG, saturation,
// the UNR division): RTPS with sf = 1, lm = 0 and MVMVA with sf = 1, lm = 0, no translation. Written from the psx-spx
// description of the GTE (the same rules as src/interp/gte.cpp, which is a dev-runtime component the product code does not
// link). Used by gt2view/particles.cpp and gt2view/glow.cpp.
#include <algorithm>
#include <array>
#include <cstdint>

namespace gt2view::psx {

// FLAG bits that raise the error summary (bit 31): 30..23 and 18..13 (IR3 saturation, bit 22, and IR0, bit 12, do not).
constexpr uint32_t kFlagErrorBits = 0x7F87E000u;

// The unsigned Newton-Raphson division of RTPS / RTPT: min(0x1FFFF, H * 0x10000 / SZ3) rounded the way the hardware does
// (the reciprocal table is generated by its defining formula); `overflow` = FLAG bit 17 (H >= 2 * SZ3).
inline uint32_t GteDivide(uint32_t h, uint32_t sz3, bool& overflow) {
    overflow = false;
    if (!(h < sz3 * 2)) {
        overflow = true;
        return 0x1FFFF;
    }
    static const std::array<uint8_t, 0x101> table = [] {
        std::array<uint8_t, 0x101> t{};
        for (int i = 0; i < 0x101; i++) t[size_t(i)] = uint8_t(std::max(0, (0x40000 / (i + 0x100) + 1) / 2 - 0x101));
        return t;
    }();
    int z = 0;
    while (z < 16 && !((sz3 << z) & 0x8000u)) z++;
    const uint64_t n = uint64_t(h) << z;
    uint32_t d = (sz3 << z) & 0xFFFFu;
    const uint32_t u = uint32_t(table[(d - 0x7FC0u) >> 7]) + 0x101u;
    d = uint32_t((0x2000080u - uint64_t(d) * u) >> 8);
    d = uint32_t((0x0000080u + uint64_t(d) * u) >> 8);
    const uint64_t q = (n * d + 0x8000u) >> 16;
    return q > 0x1FFFF ? 0x1FFFFu : uint32_t(q);
}

struct RtpsResult {
    int32_t mac[3] = {};   // MAC1..3
    int16_t ir[3] = {};    // IR1..3
    uint16_t sz3 = 0;
    int16_t sx = 0, sy = 0; // SXY2
    int32_t mac0 = 0;      // DQB + DQA * q
    uint32_t flag = 0;
    bool Error() const { return (flag & kFlagErrorBits) != 0; }
};

// RTPS, sf = 1, lm = 0 (IR saturated to -0x8000..0x7FFF).
inline RtpsResult Rtps(const int16_t rt[3][3], const int32_t tr[3], int32_t ofx, int32_t ofy, uint16_t h, int16_t dqa, int32_t dqb, int16_t vx, int16_t vy,
                       int16_t vz) {
    RtpsResult r;
    int64_t raw3 = 0;
    for (int i = 0; i < 3; i++) {
        const int64_t m = int64_t(tr[i]) * 0x1000 + int64_t(rt[i][0]) * vx + int64_t(rt[i][1]) * vy + int64_t(rt[i][2]) * vz;
        if (m > 0x7FFFFFFFFFFLL) r.flag |= 1u << (30 - i);
        else if (m < -0x80000000000LL) r.flag |= 1u << (27 - i);
        const int64_t shifted = m >> 12;
        r.mac[i] = int32_t(uint32_t(uint64_t(shifted)));
        if (i == 2) raw3 = m;
        const int32_t v = r.mac[i];
        if (v < -0x8000 || v > 0x7FFF) r.flag |= 1u << (24 - i);
        r.ir[i] = int16_t(std::clamp(v, -0x8000, 0x7FFF));
    }
    const int64_t z = raw3 >> 12;
    if (z < 0 || z > 0xFFFF) r.flag |= 1u << 18;
    r.sz3 = uint16_t(std::clamp<int64_t>(z, 0, 0xFFFF));
    bool overflow = false;
    const uint32_t q = GteDivide(h, r.sz3, overflow);
    if (overflow) r.flag |= 1u << 17;
    auto mac0Check = [&](int64_t v) {
        if (v > 0x7FFFFFFFLL) r.flag |= 1u << 16;
        else if (v < -0x80000000LL) r.flag |= 1u << 15;
    };
    const int64_t sx = int64_t(q) * r.ir[0] + ofx;
    mac0Check(sx);
    const int64_t x = sx >> 16;
    if (x < -0x400 || x > 0x3FF) r.flag |= 1u << 14;
    r.sx = int16_t(std::clamp<int64_t>(x, -0x400, 0x3FF));
    const int64_t sy = int64_t(q) * r.ir[1] + ofy;
    mac0Check(sy);
    const int64_t y = sy >> 16;
    if (y < -0x400 || y > 0x3FF) r.flag |= 1u << 13;
    r.sy = int16_t(std::clamp<int64_t>(y, -0x400, 0x3FF));
    const int64_t dq = int64_t(q) * dqa + dqb;
    mac0Check(dq);
    r.mac0 = int32_t(uint32_t(uint64_t(dq)));
    const int64_t ir0 = dq >> 12;
    if (ir0 < 0 || ir0 > 0x1000) r.flag |= 1u << 12;
    if (r.flag & kFlagErrorBits) r.flag |= 0x80000000u;
    return r;
}

// MVMVA, sf = 1, lm = 0, cv = none: IR = saturate((M . v) >> 12); returns the IR registers.
inline std::array<int16_t, 3> Mvmva(const int16_t m[3][3], const int16_t v[3]) {
    std::array<int16_t, 3> ir{};
    for (int i = 0; i < 3; i++) {
        const int64_t s = (int64_t(m[i][0]) * v[0] + int64_t(m[i][1]) * v[1] + int64_t(m[i][2]) * v[2]) >> 12;
        ir[size_t(i)] = int16_t(std::clamp<int64_t>(int32_t(uint32_t(uint64_t(s))), -0x8000, 0x7FFF));
    }
    return ir;
}
// The MAC registers of the same (the 32-bit results before saturation).
inline std::array<int32_t, 3> MvmvaMac(const int16_t m[3][3], const int16_t v[3]) {
    std::array<int32_t, 3> mac{};
    for (int i = 0; i < 3; i++)
        mac[size_t(i)] = int32_t(uint32_t(uint64_t((int64_t(m[i][0]) * v[0] + int64_t(m[i][1]) * v[1] + int64_t(m[i][2]) * v[2]) >> 12)));
    return mac;
}

// LZCS / LZCR: the number of leading bits equal to the sign bit (32 for 0 and -1).
inline int LeadingSignBits(int32_t v) {
    uint32_t u = v < 0 ? ~uint32_t(v) : uint32_t(v);
    int n = 0;
    while (n < 32 && !(u & 0x80000000u)) { u <<= 1; n++; }
    return n;
}

} // namespace gt2view::psx
